# Generated by Django 3.2.8 on 2021-10-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='summary',
            field=models.CharField(default='Qisqa matn qoshildi!1', max_length=300),
        ),
    ]
